apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-deploy-sample-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  ingressClassName: traefik  # <--- Change this from 'nginx' to 'traefik'
  rules:
    - host: nodesampledeploy-techb.duckdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: node-deploy-sample-service
                port:
                  number: 80