apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-deploy-sample-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: nodesampledeploy-techb.duckdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: node-deploy-sample-service
                port:
                  number: 80
