apiVersion: v1
kind: Service
metadata:
  name: node-deploy-sample-service
spec:
  type: NodePort
  selector:
    app: node-deploy-sample
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007
